---

- name: add visual studio code apt key
  apt_key:
    url: "{{ vscode_apt_key }}"

- name: add visual studio code repo
  apt_repository:
    repo: "{{ vscode_repo }}"
    state: present
    filename: vscode

- name: install visual studio code
  apt:
    name: code
    force_apt_get: yes

- name: install visual studio code  extensions
  command: code --install-extension {{ item }}
  with_items: "{{ vscode_extensions }}"
  become: yes
  become_user: "{{ username }}"

...