---

- name: add kubectl apt key
  apt_key:
    url: "{{ kubectl_apt_key }}"

- name: add kubectl repo
  apt_repository:
    repo: "{{ kubectl_repo }}"
    state: present
    filename: kubectl

- name: install kubectl
  apt:
    name: kubectl
    force_apt_get: yes

...