---

- name: generate SSH key
  user:
    name: "{{ username }}"
    generate_ssh_key: yes
    ssh_key_type: ed25519
    ssh_key_file: .ssh/id_ed25519
    ssh_key_passphrase: "{{ssh_passphrase}}"
    ssh_key_comment: "{{ username }}@{{ hostname}}"
    force: no
...