---

- name: add google chrome apt key
  apt_key:
    url: "{{ google_chrome_apt_key }}"

- name: add google chrome repo
  apt_repository:
    repo: "{{ google_chrome_repo }}"
    state: present
    filename: google-chrome

- name: install google chrome
  apt:
    name: google-chrome-stable
    force_apt_get: yes

...